version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_WS_BASE_URL: ${REACT_APP_WS_BASE_URL}
    depends_on:
      - backend
    networks:
      - app-network

# redis:
#   image: "redis:alpine"
#   ports:
#     - "6379:6379"
#   networks:
#     - app-network

networks:
  app-network:
    driver: bridge
